-- Neural Critic Commerce & Price Intelligence V1
-- Adds a public-read commerce catalog without allowing anonymous writes.

create table if not exists public.commerce_retailers (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  name text not null,
  homepage_url text,
  affiliate_network text,
  region text not null default 'global',
  active boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.commerce_products (
  id uuid primary key default gen_random_uuid(),
  game_id uuid references public.games(id) on delete set null,
  slug text not null unique,
  name text not null,
  category text not null default 'other' check (category in ('game','hardware','component','storage','display','input','audio','controller','accessory','other')),
  product_type text,
  brand text,
  model text,
  platform text,
  image_url text,
  image_alt text,
  msrp numeric(12,2) check (msrp is null or msrp >= 0),
  currency text not null default 'USD' check (char_length(currency) = 3),
  specs jsonb not null default '{}'::jsonb,
  featured boolean not null default false,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.commerce_offers (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references public.commerce_products(id) on delete cascade,
  retailer_id uuid not null references public.commerce_retailers(id) on delete cascade,
  external_id text,
  destination_url text not null,
  affiliate_url text,
  price numeric(12,2) not null check (price >= 0),
  list_price numeric(12,2) check (list_price is null or list_price >= 0),
  currency text not null default 'USD' check (char_length(currency) = 3),
  availability text not null default 'unknown' check (availability in ('in_stock','out_of_stock','preorder','backorder','unknown')),
  item_condition text not null default 'new' check (item_condition in ('new','used','refurbished','digital','unknown')),
  region text not null default 'global',
  is_affiliate boolean not null default false,
  source text not null default 'manual',
  fetched_at timestamptz not null default now(),
  expires_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (retailer_id, external_id)
);

create table if not exists public.commerce_price_history (
  id bigint generated by default as identity primary key,
  offer_id uuid not null references public.commerce_offers(id) on delete cascade,
  price numeric(12,2) not null check (price >= 0),
  list_price numeric(12,2) check (list_price is null or list_price >= 0),
  availability text not null default 'unknown' check (availability in ('in_stock','out_of_stock','preorder','backorder','unknown')),
  captured_at timestamptz not null default now()
);

create table if not exists public.commerce_article_products (
  article_id uuid not null references public.articles(id) on delete cascade,
  product_id uuid not null references public.commerce_products(id) on delete cascade,
  placement text not null default 'where_to_buy',
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  primary key (article_id, product_id, placement)
);

create index if not exists commerce_products_game_id_idx on public.commerce_products(game_id);
create index if not exists commerce_products_category_idx on public.commerce_products(category);
create index if not exists commerce_products_featured_idx on public.commerce_products(featured) where active = true;
create index if not exists commerce_offers_product_id_idx on public.commerce_offers(product_id);
create index if not exists commerce_offers_retailer_id_idx on public.commerce_offers(retailer_id);
create index if not exists commerce_offers_price_idx on public.commerce_offers(price) where availability in ('in_stock','preorder');
create index if not exists commerce_offers_fetched_at_idx on public.commerce_offers(fetched_at desc);
create index if not exists commerce_price_history_offer_time_idx on public.commerce_price_history(offer_id, captured_at desc);
create index if not exists commerce_article_products_article_idx on public.commerce_article_products(article_id, sort_order);

alter table public.commerce_retailers enable row level security;
alter table public.commerce_products enable row level security;
alter table public.commerce_offers enable row level security;
alter table public.commerce_price_history enable row level security;
alter table public.commerce_article_products enable row level security;

drop policy if exists "Public can read active commerce retailers" on public.commerce_retailers;
create policy "Public can read active commerce retailers" on public.commerce_retailers
for select to anon, authenticated using (active = true);

drop policy if exists "Public can read active commerce products" on public.commerce_products;
create policy "Public can read active commerce products" on public.commerce_products
for select to anon, authenticated using (active = true);

drop policy if exists "Public can read commerce offers" on public.commerce_offers;
create policy "Public can read commerce offers" on public.commerce_offers
for select to anon, authenticated using (true);

drop policy if exists "Public can read commerce price history" on public.commerce_price_history;
create policy "Public can read commerce price history" on public.commerce_price_history
for select to anon, authenticated using (true);

drop policy if exists "Public can read article commerce links" on public.commerce_article_products;
create policy "Public can read article commerce links" on public.commerce_article_products
for select to anon, authenticated using (true);

grant select on public.commerce_retailers to anon, authenticated;
grant select on public.commerce_products to anon, authenticated;
grant select on public.commerce_offers to anon, authenticated;
grant select on public.commerce_price_history to anon, authenticated;
grant select on public.commerce_article_products to anon, authenticated;
grant usage, select on sequence public.commerce_price_history_id_seq to anon, authenticated;

comment on table public.commerce_products is 'Canonical Neural Critic commerce products. Game products may reference public.games; hardware remains independent.';
comment on table public.commerce_offers is 'Retailer-specific current offers. affiliate_url is optional and must be marked sponsored when rendered.';
comment on table public.commerce_price_history is 'Historical snapshots used for price trend and historical-low intelligence.';
comment on table public.commerce_article_products is 'Explicit editorial-to-commerce relationships used for Where to Buy modules.';
