-- Neural Critic Search Intelligence V1
-- Private, editor-readable storage for finalized Google Search Console metrics.
-- Writes are performed only by trusted server-side tooling using the service role.

create table if not exists public.search_console_daily (
  id bigint generated by default as identity primary key,
  metric_date date not null,
  site_url text not null,
  search_type text not null default 'web',
  query text not null default '',
  page_url text not null,
  story_slug text,
  clicks double precision not null default 0 check (clicks >= 0),
  impressions double precision not null default 0 check (impressions >= 0),
  ctr double precision not null default 0 check (ctr >= 0 and ctr <= 1),
  position double precision not null default 0 check (position >= 0),
  synced_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  constraint search_console_daily_identity_key unique (metric_date, site_url, search_type, query, page_url)
);

create index if not exists search_console_daily_date_idx
  on public.search_console_daily (metric_date desc);

create index if not exists search_console_daily_story_date_idx
  on public.search_console_daily (story_slug, metric_date desc)
  where story_slug is not null;

create index if not exists search_console_daily_page_date_idx
  on public.search_console_daily (page_url, metric_date desc);

alter table public.search_console_daily enable row level security;

-- Search performance is newsroom intelligence, not public-site data.
revoke all on table public.search_console_daily from public, anon, authenticated;
grant select on table public.search_console_daily to authenticated;

drop policy if exists "Editors can read Search Console intelligence" on public.search_console_daily;
create policy "Editors can read Search Console intelligence"
on public.search_console_daily for select
to authenticated
using (
  exists (
    select 1
    from public.editor_profiles ep
    where ep.user_id = (select auth.uid())
      and ep.role = any (array['editor'::text, 'admin'::text])
  )
);

comment on table public.search_console_daily is
  'Private finalized Search Console query/page metrics used by Neural Critic newsroom intelligence.';
comment on column public.search_console_daily.story_slug is
  'Derived Neural Critic story slug when page_url maps to a canonical /stories/<slug>/ or legacy article URL.';
